### ISSUE TITLE
Kakashi section

### ISSUE THREAD

**Issue by JanjuaArsh** [JanjuaArsh/JanjuaArsh.github.io#2]
to do:
make two htmls for kakashi
1. one html containing description, stories of kakashi. images.
2. quotes inspiration lessons from kakashi hatake- his life with his friends.

-both files in html folder
-link to both htmls in index.html file i.e in content
- give proper title and description.
-use inline css

@Vinkal Kandal

**Comment by DeViL3998** [comment]
can i do this?

**Comment by JanjuaArsh** [comment]
@DeViL3998 sure
