### ISSUE TITLE
Index.html - homepage html

### ISSUE THREAD

**Issue by JanjuaArsh** [JanjuaArsh/JanjuaArsh.github.io#3]
create content
1. should be in hierarchy
2. should be descriptive and easy to read.
3. should have proper titles.
4. create only for desktop view.

optimise html.
- reach above 90% speed
- add proper title and description
- add proper html

**Comment by shubham860** [comment]
will u please elaborate the point 1,2,3

**Comment by JanjuaArsh** [comment]
Content is some thing that helps you reach to other pages.

**Comment by JanjuaArsh** [comment]
Done with the basis content menu.
